### ISSUE TITLE
Doc: Unclear connection to "official" provider

### ISSUE THREAD

**Issue by stevenpitts** [CrowdStrike/terraform-provider-crowdstrike#27]
Going through the official CrowdStrike AWS registration process, I am provided with instructions to use this provider:
```
      crowdstrike = {
        source  = "cs-prod-cloudconnect-templates.s3.amazonaws.com/crowdstrike/crowdstrike"
        version = ">= 0.3.0"
      }
```
What is the connection between that provider source and this one?

**Comment by ffalor** [comment]
Hey @stevenpitts the provider you linked is used to register cloud accounts for CSPM.

The provider in this repo ([published here on the terraform registry](https://registry.terraform.io/providers/CrowdStrike/crowdstrike/latest)) is currently managing other resources in the Falcon console.

For example you can use this provider to create a manage the following resources:

- host groups
- sensor update policies
- prevention policies
- filevantage policies

There are plans to add more resources to this provider.

**Comment by stevenpitts** [comment]
@ffalor That makes sense, thank you!
