### ISSUE TITLE
Bug: imported static host group error due to `assignment_rule` attribute

### ISSUE THREAD

**Issue by stmyers** [CrowdStrike/terraform-provider-crowdstrike#31]
Hi, first off really happy to finally see an official TF provider for CrowdStrike!  🫶 

I started exploring this today and wanted to manage host groups via TF, so I imported a static host group.

After importing, I checked the state file and I updated the TF code to match but there was a slight formatting change to the description which triggered an update to the resource.  Not a problem - I ran the apply to let TF update the description, but I got an error:

```shell
Error: Error updating host group
with crowdstrike_host_group.my_host_group
on host_groups.tf line 1, in resource "crowdstrike_host_group" "my_host_group":
resource "crowdstrike_host_group" "my_host_group" {
Group type much be dynamic in order to use assignment_rule
```

Here is the code:
```hcl
resource "crowdstrike_host_group" "my_host_group" {
  name            = "My Host Group"
  type            = "static"
  assignment_rule = "device_id:[''],hostname:['MY-HOST-1', 'MY-HOST-2', 'MY-HOST-3']"
  description     = <<-EOT
      This Group is for scoping certain hosts explicitly.

      See https://link-to-doc
      EOT
}
```

I didn't write the code by-hand, I read the values in state after importing the resource.  It makes sense that an `assignment_rule` shouldn't be used for a static host group, but It's unclear how `type = "static"` is supposed to be used for assigning hosts to a group, and what is imported into state doesn't appear compatible.

Here's `terraform state show` output after import:
```hcl
$ terraform state show crowdstrike_host_group.my_host_group

# crowdstrike_host_group.my_host_group:
resource "crowdstrike_host_group" "my_host_group" {
    assignment_rule = "device_id:[''],hostname:['MY-HOST-1', 'MY-HOST-2', 'MY-HOST-3']"
    description     = <<-EOT
        This Group is for scoping certain hosts explicitly.

        See https://link-to-doc
    EOT
    id              = "<redacted>"
    name            = "My Host Group"
    type            = "static"
}
```

**Comment by ffalor** [comment]
@stmyers great find and thank you for the details bug report.. Let me look into this and I'll get a fix out as soon as possible.

**Comment by ffalor** [comment]
I've started work on this. It looks like I may need to introduce two attributes

`hostnames` for `static` host groups` and `host_ids` for `staticByID` host groups.

So your resource would look like this:

```terraform
resource "crowdstrike_host_group" "my_host_group" {
    hostnames = ["MY-HOST-1",  "MY-HOST-2",  "MY-HOST-3"]
    description     = <<-EOT
        This Group is for scoping certain hosts explicitly.

        See https://link-to-doc
    EOT
    id              = "<redacted>"
    name            = "My Host Group"
    type            = "static"
}
``` 

Let me know if you have any concerns with the above approach.

**Comment by ffalor** [comment]
Newest version should solve this.

```terraform
    crowdstrike = {
      source = "CrowdStrike/crowdstrike"
      version = "0.0.6"
    }
```
