### ISSUE TITLE
Cloudformation template issue

### ISSUE THREAD

**Issue by jsolares-nex** [CrowdStrike/terraform-provider-crowdstrike#48]
I'm using this provider for CrowdStrike CSPM, but I get the following error when doing the terraform Apply:

│ Error: creating CloudFormation StackSet (CrowdStrike-CSPM-Integration-Root-EB): operation error CloudFormation: CreateStackSet, https response error StatusCode: 400, RequestID: 901fbf17-0d19-4196-845d-2beb77aa68a7, api error ValidationError: Object referenced by https://cs-prod-cloudconnect-templates.s3.amazonaws.com/aws_cspm_cloudformation_eb_v2.json is not accessible.

I don't have any SCP level restrictions in my AWS account and I can't find any related documentation, can you help me?

**Comment by ffalor** [comment]
Hey @jsolares-nex you should reach out to support or your TAM for this issue. Currently, this provider is not used in the CSPM registration process so this issue isn't something we can fix in this repository. #27
