### ISSUE TITLE
Issue with CrowdStrike Terraform Provider

### ISSUE THREAD

**Issue by DiegoVazquezNanini** [CrowdStrike/terraform-provider-crowdstrike#50]
I'm experiencing an issue with the CrowdStrike Terraform provider.
When attempting to use the resource `crowdstrike_prevention_policy_linux`, I am unable to reference a host group. The configuration only functions correctly if I hardcode the host group ID directly into the list. I have attached an image showing the value conversion error. I understand that the host group ID might not be available until Terraform creates the resources, but I believe the provider should be able to handle this scenario. Could you please let me know if there is a workaround for this issue or an estimate on when it might be addressed? I am available for further questions if needed. 

Using 
Terraform `v1.8.3` on darwin_arm64 and `crowdstrike/crowdstrike v0.0.7`

![Screenshot 2024-11-06 at 14 38 02](https://github.com/user-attachments/assets/edffc2f7-9e05-44f9-81dd-7e98041c6fd6)
![Screenshot 2024-11-06 at 14 38 15](https://github.com/user-attachments/assets/5a3b2a06-e613-43d9-99ca-981efbd14c94)
![Screenshot 2024-11-06 at 14 38 42](https://github.com/user-attachments/assets/66a07286-4160-41f9-a0e5-1d0f2beff84f)
![Screenshot 2024-11-06 at 14 39 07](https://github.com/user-attachments/assets/689e0a89-0186-4b3b-90f3-f3d6c8219127)

**Comment by ffalor** [comment]
Hey @DiegoVazquezNanini i resolved this issue yesterday! `v0.0.8` has the fix. Please upgrade to that version and you should be able to do this.

**Comment by DiegoVazquezNanini** [comment]
Hi @ffalor 
Thanks for doing this, but I still get a similar error with `0.0.8`
Even passing a variable with an empty list to `host_groups` produces this error.

![Screenshot 2024-11-07 at 08 34 50](https://github.com/user-attachments/assets/242cded8-aa4c-44bb-9677-1eb47332e003)

**Comment by DiegoVazquezNanini** [comment]
Let me know if you prefer that I raise another issue.
