### ISSUE TITLE
crowdstrike_prevention_policy_linux can't handle references in the host_groups

### ISSUE THREAD

**Issue by DiegoVazquezNanini** [CrowdStrike/terraform-provider-crowdstrike#51]
We get a Value conversion error when passing a reference to host_groups. 
After updating to `0.0.8` the error shows a different type. 

[issue 47](https://github.com/CrowdStrike/terraform-provider-crowdstrike/issues/47)
[issue 50](https://github.com/CrowdStrike/terraform-provider-crowdstrike/issues/50)

![383877879-242cded8-aa4c-44bb-9677-1eb47332e003](https://github.com/user-attachments/assets/c8aaa0a7-0811-4942-8145-a967e0f8818e)

**Comment by ffalor** [comment]
Thanks for the report @DiegoVazquezNanini, I think I've identified the issue.

in #47 when you provide a reference to a resource the path is known, but the values are unknown so I added checks to fix that.

When you provide a reference the way you do in your example the whole path is unknown.

Working on a fix.

**Comment by DiegoVazquezNanini** [comment]
Yes, I understand the root cause of the problem now, but this is a common thing in Terraform that I assumed was handled automatically, but it seems that is not the case.

**Comment by ffalor** [comment]
My comment was more for my records incase I come across this again in the future. The pr #52 which fixed this error is what closed the issue. I reopened the issue while I work on publishing a release.

**Comment by ffalor** [comment]
`v0.0.9` has been released & should fix your issue! Thanks for reporting it!

```terraform
terraform {
  required_providers {
    crowdstrike = {
      source = "CrowdStrike/crowdstrike"
      version = "0.0.9"
    }
  }
}
```

**Comment by DiegoVazquezNanini** [comment]
Thank you @ffalor  🙇🏼 
I will test it and get back to you. Seem working during my first local test.

**Comment by DiegoVazquezNanini** [comment]
This solved the issue. Thank you 🙇🏼
